[package]
name        = "salada"
version     = "0.0.2"
description = "JMAP server"
license     = "MIT"
authors     = [ "Robert Norris <robn@robn.io>" ]
repository  = "https://github.com/robn/salada"

[[bin]]
name = "salada"

[dependencies]
jmap = "*"
hyper = "*"
rustc-serialize = "*"
rusqlite = "*"
log = "*"
time = "*"
